/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as anonRouteRouteImport } from './routes/(anon)/route'
import { Route as anonIndexRouteImport } from './routes/(anon)/index'
import { Route as authJoinGameRouteImport } from './routes/(auth)/join-game'
import { Route as authCreateGameRouteImport } from './routes/(auth)/create-game'
import { Route as anonRegisterRouteImport } from './routes/(anon)/register'
import { Route as anonLoginRouteImport } from './routes/(anon)/login'

const anonRouteRoute = anonRouteRouteImport.update({
  id: '/(anon)',
  getParentRoute: () => rootRouteImport,
} as any)
const anonIndexRoute = anonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => anonRouteRoute,
} as any)
const authJoinGameRoute = authJoinGameRouteImport.update({
  id: '/(auth)/join-game',
  path: '/join-game',
  getParentRoute: () => rootRouteImport,
} as any)
const authCreateGameRoute = authCreateGameRouteImport.update({
  id: '/(auth)/create-game',
  path: '/create-game',
  getParentRoute: () => rootRouteImport,
} as any)
const anonRegisterRoute = anonRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => anonRouteRoute,
} as any)
const anonLoginRoute = anonLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => anonRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof anonLoginRoute
  '/register': typeof anonRegisterRoute
  '/create-game': typeof authCreateGameRoute
  '/join-game': typeof authJoinGameRoute
  '/': typeof anonIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof anonLoginRoute
  '/register': typeof anonRegisterRoute
  '/create-game': typeof authCreateGameRoute
  '/join-game': typeof authJoinGameRoute
  '/': typeof anonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(anon)': typeof anonRouteRouteWithChildren
  '/(anon)/login': typeof anonLoginRoute
  '/(anon)/register': typeof anonRegisterRoute
  '/(auth)/create-game': typeof authCreateGameRoute
  '/(auth)/join-game': typeof authJoinGameRoute
  '/(anon)/': typeof anonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/create-game' | '/join-game' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/create-game' | '/join-game' | '/'
  id:
    | '__root__'
    | '/(anon)'
    | '/(anon)/login'
    | '/(anon)/register'
    | '/(auth)/create-game'
    | '/(auth)/join-game'
    | '/(anon)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  anonRouteRoute: typeof anonRouteRouteWithChildren
  authCreateGameRoute: typeof authCreateGameRoute
  authJoinGameRoute: typeof authJoinGameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(anon)': {
      id: '/(anon)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof anonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(anon)/': {
      id: '/(anon)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof anonIndexRouteImport
      parentRoute: typeof anonRouteRoute
    }
    '/(auth)/join-game': {
      id: '/(auth)/join-game'
      path: '/join-game'
      fullPath: '/join-game'
      preLoaderRoute: typeof authJoinGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/create-game': {
      id: '/(auth)/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof authCreateGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(anon)/register': {
      id: '/(anon)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof anonRegisterRouteImport
      parentRoute: typeof anonRouteRoute
    }
    '/(anon)/login': {
      id: '/(anon)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof anonLoginRouteImport
      parentRoute: typeof anonRouteRoute
    }
  }
}

interface anonRouteRouteChildren {
  anonLoginRoute: typeof anonLoginRoute
  anonRegisterRoute: typeof anonRegisterRoute
  anonIndexRoute: typeof anonIndexRoute
}

const anonRouteRouteChildren: anonRouteRouteChildren = {
  anonLoginRoute: anonLoginRoute,
  anonRegisterRoute: anonRegisterRoute,
  anonIndexRoute: anonIndexRoute,
}

const anonRouteRouteWithChildren = anonRouteRoute._addFileChildren(
  anonRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  anonRouteRoute: anonRouteRouteWithChildren,
  authCreateGameRoute: authCreateGameRoute,
  authJoinGameRoute: authJoinGameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
