/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as anonRouteRouteImport } from './routes/(anon)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authJoinGameRouteImport } from './routes/(auth)/join-game'
import { Route as authEventsRouteImport } from './routes/(auth)/events'
import { Route as authCreateGameRouteImport } from './routes/(auth)/create-game'
import { Route as anonRegisterRouteImport } from './routes/(anon)/register'
import { Route as anonLoginRouteImport } from './routes/(anon)/login'
import { Route as authLobbyRouteRouteImport } from './routes/(auth)/lobby/route'
import { Route as authLobbyIndexRouteImport } from './routes/(auth)/lobby/index'
import { Route as authLobbyJoinRouteImport } from './routes/(auth)/lobby/join'
import { Route as authLobbyCodeRouteImport } from './routes/(auth)/lobby/$code'
import { Route as authGameGameidRouteImport } from './routes/(auth)/game/$gameid'
import { Route as authEventsGameidRouteImport } from './routes/(auth)/events/$gameid'

const anonRouteRoute = anonRouteRouteImport.update({
  id: '/(anon)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authJoinGameRoute = authJoinGameRouteImport.update({
  id: '/(auth)/join-game',
  path: '/join-game',
  getParentRoute: () => rootRouteImport,
} as any)
const authEventsRoute = authEventsRouteImport.update({
  id: '/(auth)/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const authCreateGameRoute = authCreateGameRouteImport.update({
  id: '/(auth)/create-game',
  path: '/create-game',
  getParentRoute: () => rootRouteImport,
} as any)
const anonRegisterRoute = anonRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => anonRouteRoute,
} as any)
const anonLoginRoute = anonLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => anonRouteRoute,
} as any)
const authLobbyRouteRoute = authLobbyRouteRouteImport.update({
  id: '/(auth)/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const authLobbyIndexRoute = authLobbyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLobbyRouteRoute,
} as any)
const authLobbyJoinRoute = authLobbyJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => authLobbyRouteRoute,
} as any)
const authLobbyCodeRoute = authLobbyCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => authLobbyRouteRoute,
} as any)
const authGameGameidRoute = authGameGameidRouteImport.update({
  id: '/(auth)/game/$gameid',
  path: '/game/$gameid',
  getParentRoute: () => rootRouteImport,
} as any)
const authEventsGameidRoute = authEventsGameidRouteImport.update({
  id: '/$gameid',
  path: '/$gameid',
  getParentRoute: () => authEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby': typeof authLobbyRouteRouteWithChildren
  '/login': typeof anonLoginRoute
  '/register': typeof anonRegisterRoute
  '/create-game': typeof authCreateGameRoute
  '/events': typeof authEventsRouteWithChildren
  '/join-game': typeof authJoinGameRoute
  '/events/$gameid': typeof authEventsGameidRoute
  '/game/$gameid': typeof authGameGameidRoute
  '/lobby/$code': typeof authLobbyCodeRoute
  '/lobby/join': typeof authLobbyJoinRoute
  '/lobby/': typeof authLobbyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof anonLoginRoute
  '/register': typeof anonRegisterRoute
  '/create-game': typeof authCreateGameRoute
  '/events': typeof authEventsRouteWithChildren
  '/join-game': typeof authJoinGameRoute
  '/events/$gameid': typeof authEventsGameidRoute
  '/game/$gameid': typeof authGameGameidRoute
  '/lobby/$code': typeof authLobbyCodeRoute
  '/lobby/join': typeof authLobbyJoinRoute
  '/lobby': typeof authLobbyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(anon)': typeof anonRouteRouteWithChildren
  '/(auth)/lobby': typeof authLobbyRouteRouteWithChildren
  '/(anon)/login': typeof anonLoginRoute
  '/(anon)/register': typeof anonRegisterRoute
  '/(auth)/create-game': typeof authCreateGameRoute
  '/(auth)/events': typeof authEventsRouteWithChildren
  '/(auth)/join-game': typeof authJoinGameRoute
  '/(auth)/events/$gameid': typeof authEventsGameidRoute
  '/(auth)/game/$gameid': typeof authGameGameidRoute
  '/(auth)/lobby/$code': typeof authLobbyCodeRoute
  '/(auth)/lobby/join': typeof authLobbyJoinRoute
  '/(auth)/lobby/': typeof authLobbyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lobby'
    | '/login'
    | '/register'
    | '/create-game'
    | '/events'
    | '/join-game'
    | '/events/$gameid'
    | '/game/$gameid'
    | '/lobby/$code'
    | '/lobby/join'
    | '/lobby/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/create-game'
    | '/events'
    | '/join-game'
    | '/events/$gameid'
    | '/game/$gameid'
    | '/lobby/$code'
    | '/lobby/join'
    | '/lobby'
  id:
    | '__root__'
    | '/'
    | '/(anon)'
    | '/(auth)/lobby'
    | '/(anon)/login'
    | '/(anon)/register'
    | '/(auth)/create-game'
    | '/(auth)/events'
    | '/(auth)/join-game'
    | '/(auth)/events/$gameid'
    | '/(auth)/game/$gameid'
    | '/(auth)/lobby/$code'
    | '/(auth)/lobby/join'
    | '/(auth)/lobby/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  anonRouteRoute: typeof anonRouteRouteWithChildren
  authLobbyRouteRoute: typeof authLobbyRouteRouteWithChildren
  authCreateGameRoute: typeof authCreateGameRoute
  authEventsRoute: typeof authEventsRouteWithChildren
  authJoinGameRoute: typeof authJoinGameRoute
  authGameGameidRoute: typeof authGameGameidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(anon)': {
      id: '/(anon)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof anonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/join-game': {
      id: '/(auth)/join-game'
      path: '/join-game'
      fullPath: '/join-game'
      preLoaderRoute: typeof authJoinGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/events': {
      id: '/(auth)/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof authEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/create-game': {
      id: '/(auth)/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof authCreateGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(anon)/register': {
      id: '/(anon)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof anonRegisterRouteImport
      parentRoute: typeof anonRouteRoute
    }
    '/(anon)/login': {
      id: '/(anon)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof anonLoginRouteImport
      parentRoute: typeof anonRouteRoute
    }
    '/(auth)/lobby': {
      id: '/(auth)/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof authLobbyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/lobby/': {
      id: '/(auth)/lobby/'
      path: '/'
      fullPath: '/lobby/'
      preLoaderRoute: typeof authLobbyIndexRouteImport
      parentRoute: typeof authLobbyRouteRoute
    }
    '/(auth)/lobby/join': {
      id: '/(auth)/lobby/join'
      path: '/join'
      fullPath: '/lobby/join'
      preLoaderRoute: typeof authLobbyJoinRouteImport
      parentRoute: typeof authLobbyRouteRoute
    }
    '/(auth)/lobby/$code': {
      id: '/(auth)/lobby/$code'
      path: '/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof authLobbyCodeRouteImport
      parentRoute: typeof authLobbyRouteRoute
    }
    '/(auth)/game/$gameid': {
      id: '/(auth)/game/$gameid'
      path: '/game/$gameid'
      fullPath: '/game/$gameid'
      preLoaderRoute: typeof authGameGameidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/events/$gameid': {
      id: '/(auth)/events/$gameid'
      path: '/$gameid'
      fullPath: '/events/$gameid'
      preLoaderRoute: typeof authEventsGameidRouteImport
      parentRoute: typeof authEventsRoute
    }
  }
}

interface anonRouteRouteChildren {
  anonLoginRoute: typeof anonLoginRoute
  anonRegisterRoute: typeof anonRegisterRoute
}

const anonRouteRouteChildren: anonRouteRouteChildren = {
  anonLoginRoute: anonLoginRoute,
  anonRegisterRoute: anonRegisterRoute,
}

const anonRouteRouteWithChildren = anonRouteRoute._addFileChildren(
  anonRouteRouteChildren,
)

interface authLobbyRouteRouteChildren {
  authLobbyCodeRoute: typeof authLobbyCodeRoute
  authLobbyJoinRoute: typeof authLobbyJoinRoute
  authLobbyIndexRoute: typeof authLobbyIndexRoute
}

const authLobbyRouteRouteChildren: authLobbyRouteRouteChildren = {
  authLobbyCodeRoute: authLobbyCodeRoute,
  authLobbyJoinRoute: authLobbyJoinRoute,
  authLobbyIndexRoute: authLobbyIndexRoute,
}

const authLobbyRouteRouteWithChildren = authLobbyRouteRoute._addFileChildren(
  authLobbyRouteRouteChildren,
)

interface authEventsRouteChildren {
  authEventsGameidRoute: typeof authEventsGameidRoute
}

const authEventsRouteChildren: authEventsRouteChildren = {
  authEventsGameidRoute: authEventsGameidRoute,
}

const authEventsRouteWithChildren = authEventsRoute._addFileChildren(
  authEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  anonRouteRoute: anonRouteRouteWithChildren,
  authLobbyRouteRoute: authLobbyRouteRouteWithChildren,
  authCreateGameRoute: authCreateGameRoute,
  authEventsRoute: authEventsRouteWithChildren,
  authJoinGameRoute: authJoinGameRoute,
  authGameGameidRoute: authGameGameidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
